name: Cleanup

on:
  pull_request:
    types: [closed, unlabeled]
    branches:
      - github-actions

env:
  GKE_CLUSTER: jx-prod
  GKE_ZONE: us-east1-b

jobs:
  cleanup:
    if: (github.event.type == 'unlabeled' && github.event.label.name == 'preview') || (contains(github.event.pull_request.labels.*.name, 'preview')
    runs-on: ubuntu-latest
    steps:

    - name: Prepare environment
      run: |
        BRANCH_NAME=${GITHUB_REF##*/}
        echo "PREVIEW_NAMESPACE=webui-nuxeo-elements-$BRANCH_NAME" >> $GITHUB_ENV

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v0.2.1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        project_id: ${{ secrets.GKE_PROJECT }}
        credentials: ${{ secrets.GKE_SA_KEY }}

    - name: Cleanup preview namespace
      if: ${{ steps.preview_ns.outputs.exists }}
      continue-on-error: true
      run: |
        kubectl delete ns -n ${PREVIEW_NAMESPACE}
