name: PR

on:
  pull_request:
    types:
      - opened
    branches:
      - master

jobs:
  jira:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - name: JIRA Login
      # XXX - atlasstin/gajira-login@ relies on rest api v3
      uses: nelsonsilva/gajira-login@dcee5e3
      env:
        JIRA_BASE_URL: http://jira.nuxeo.com
        JIRA_USER_EMAIL: hudson
        JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}
    - name: Find JIRA ticket
      id: find
      # XXX: atlasstin/gajira-find-issue-key doesn't work for PR
      uses: nelsonsilva/gajira-find-issue-key@6ef5875
    - uses: actions/github-script@0.9.0
      if: steps.find.outputs.issues
      env:
        JIRA_TICKETS: ${{ steps.find.outputs.issue }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const links = process.env.JIRA_TICKET
            .map((issue) => `- [${issue.key}](http://jira.nuxeo.com/browse/${issue.key}) ${issue.summary}`)
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `View issues in JIRA:\n${links.join('\n')}`
          })
