name: Unit Tests

on:
  push:
    branches:
      - github-actions
  pull_request:
    branches:
      - github-actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: 'https://packages.nuxeo.com/repository/npm-public/'
        scope: '@nuxeo'
    - name: Install
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        npm install --no-package-lock
        npm run bootstrap
    - name: Lint
      run: npm run lint
    - name: Test
      env:
        SAUCE_USERNAME: nuxeo-elements
        SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
      run: npm run test
    - name: Deploy
      if: github.ref == 'master'
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: npm run deploy -- --ci -t GITHUB_TOKEN
    - name: Publish
      if: github.ref == 'master'
      run: npx lerna exec --ignore @nuxeo/nuxeo-elements-storybook -- npm publish --tag SNAPSHOT
    
